apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-boot-app
  labels:
    app: spring-boot-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-application
  template:
    metadata:
      labels:
        app: spring-boot-application
    spec:
      containers:
      - name: my-spring-boot-app
        image: myacr1001.azurecr.io/sprint-boot-app:1.0-43
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-image-secret
