apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
   # protocol: TCP
  selector:
    app: spring-boot-app
